import { BlogPost } from "@/types/blog";

// Auto-generated file - DO NOT EDIT MANUALLY
// This file is generated by scripts/process-posts.js

export const posts: BlogPost[] = [
  {
    "slug": "never-order-chicken-nuggets",
    "title": "Why You Should Never Order 12 Chicken Nuggets and Fries",
    "date": "2021-08-01",
    "author": "George Costanza",
    "category": "Food Theory",
    "excerpt": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Diam mollis lectus vitae nulla malesuada amet purus sed. A condimentum tempus a egestas sodales diam cras.",
    "coverImage": "https://images.unsplash.com/photo-1562967914-608f82629710?w=800&h=600&fit=crop",
    "tags": [
      "food",
      "nutrition",
      "health"
    ],
    "content": "\n# Why You Should Never Order 12 Chicken Nuggets and Fries\n\nLet me tell you why this seemingly innocent meal choice could be problematic from multiple perspectives.\n\n## The Math Doesn't Add Up\n\nWhen you order 12 nuggets and fries, you're actually getting more food than you need. Here's the breakdown:\n\n- 12 nuggets = approximately 540 calories\n- Medium fries = approximately 380 calories\n- **Total**: 920 calories in one meal\n\n### The Nutritional Reality\n\nBut it's not just about calories. Consider:\n\n- **Sodium**: Over 1,200mg (50% of daily recommended intake)\n- **Fat**: 45-50g (mostly saturated and trans fats)\n- **Protein**: While chicken provides protein, the processing reduces nutritional value\n\n## Better Alternatives\n\nConsider these healthier options that still satisfy your cravings:\n\n1. **6 nuggets with a side salad** - Cuts calories in half while adding nutrients\n2. **Grilled chicken sandwich** - Better protein quality, fewer calories\n3. **Homemade baked nuggets** - Control ingredients and cooking method\n\n### The Economic Angle\n\nHere's something interesting: ordering 2 sets of 6 nuggets is often cheaper than ordering 12, and you get the same amount. Fast food pricing isn't always logical.\n\n## The Bottom Line\n\nI'm not saying never enjoy fast food, but being mindful about portions and combinations can make a significant difference in your health and wallet. Next time you're at the counter, pause and consider: do you really need 12?\n\nYour body (and potentially your budget) will thank you.\n",
    "readingTime": "2 min read"
  },
  {
    "slug": "traveling-greece-two-weeks",
    "title": "What Traveling Greece For 2 Weeks Taught Me About Life",
    "date": "2021-06-21",
    "author": "George Costanza",
    "category": "Travel",
    "excerpt": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Diam mollis lectus vitae nulla malesuada amet purus sed. A condimentum tempus a egestas sodales diam cras.",
    "coverImage": "https://images.unsplash.com/photo-1601581987809-a874a81309c9?w=800&h=600&fit=crop",
    "tags": [
      "travel",
      "life lessons",
      "greece"
    ],
    "content": "\n# What Traveling Greece For 2 Weeks Taught Me About Life\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Diam mollis lectus vitae nulla malesuada amet purus sed. A condimentum tempus a egestas sodales diam cras.\n\n## The Journey Begins\n\nPellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper.\n\n### Key Moments\n\nThe streets of Athens taught me patience. The islands showed me peace. And the people reminded me of what truly matters in life.\n\n## Lessons Learned\n\n1. **Embrace the unknown** - Some of the best experiences came from moments I didn't plan\n2. **Connect with locals** - Real travel happens through genuine human connection\n3. **Slow down and enjoy the moment** - Not everything needs to be captured on camera\n\n### The Power of Simplicity\n\nGreece's beauty lies in its simplicity. White-washed buildings, blue domes, and crystal-clear waters. Sometimes the most profound experiences come from the simplest things.\n\n## Reflection\n\nThis journey taught me that travel isn't just about seeing new places—it's about discovering new perspectives. Every sunset over the Aegean, every conversation with a local fisherman, every meal shared with new friends contributed to a transformation I didn't know I needed.\n\nWould I do it again? In a heartbeat. Greece doesn't just show you the world; it shows you yourself.\n",
    "readingTime": "2 min read"
  }
];

export const getPostBySlug = (slug: string): BlogPost | undefined => {
  return posts.find(post => post.slug === slug);
};

export const getPostsByCategory = (category: string): BlogPost[] => {
  return posts.filter(post => post.category.toLowerCase() === category.toLowerCase());
};

export const getAllCategories = (): string[] => {
  return Array.from(new Set(posts.map(post => post.category)));
};
