const fs = require('fs');
const path = require('path');
const matter = require('gray-matter');
const readingTime = require('reading-time');
const { glob } = require('glob');

async function processPosts() {
  // Find all markdown files in src/content/posts
  const postFiles = await glob('src/content/posts/**/*.md');
  
  const posts = postFiles.map(filePath => {
    const fileContent = fs.readFileSync(filePath, 'utf8');
    const { data, content } = matter(fileContent);
    const stats = readingTime(content);
    
    // Extract slug from filename
    const slug = path.basename(filePath, '.md');
    
    return {
      slug,
      title: data.title,
      date: data.date,
      author: data.author,
      category: data.category,
      excerpt: data.excerpt,
      coverImage: data.coverImage,
      tags: data.tags || [],
      content: content,
      readingTime: stats.text
    };
  });
  
  // Sort posts by date (newest first)
  posts.sort((a, b) => new Date(b.date) - new Date(a.date));
  
  // Generate TypeScript file
  const output = `import { BlogPost } from "@/types/blog";

// Auto-generated file - DO NOT EDIT MANUALLY
// This file is generated by scripts/process-posts.js

export const posts: BlogPost[] = ${JSON.stringify(posts, null, 2)};

export const getPostBySlug = (slug: string): BlogPost | undefined => {
  return posts.find(post => post.slug === slug);
};

export const getPostsByCategory = (category: string): BlogPost[] => {
  return posts.filter(post => post.category.toLowerCase() === category.toLowerCase());
};

export const getAllCategories = (): string[] => {
  return Array.from(new Set(posts.map(post => post.category)));
};
`;
  
  fs.writeFileSync('src/lib/posts.ts', output);
  console.log(`✅ Processed ${posts.length} blog posts`);
}

processPosts().catch(console.error);
